"""
List of all available GDAL drivers for vector and raster data formats
in Conda environment

Generated with::

    from osgeo import gdal

    drivers = [gdal.GetDriver(i) for i in range(gdal.GetDriverCount())]
    vector = [d.ShortName for d in drivers if d.GetMetadataItem(gdal.DCAP_VECTOR) == "YES"]
    raster = [d.ShortName for d in drivers if d.GetMetadataItem(gdal.DCAP_RASTER) == "YES"]

    print("Vector drivers:")
    print(sorted(vector))

    print("\nRaster drivers:")
    print(sorted(raster))

.. todo::

    Some of these may not be renderable in MapServer. Add a flag for those
    so an error message can be raised.
"""

VECTOR_DRIVERS = [
    "ADBC",
    "AIVector",
    "AVCBin",
    "AVCE00",
    "AmigoCloud",
    "CAD",
    "CSV",
    "CSW",
    "Carto",
    "DGN",
    "DXF",
    "EDIGEO",
    "EEDA",
    "ESRI Shapefile",
    "ESRIJSON",
    "Elasticsearch",
    "FlatGeobuf",
    "GDALG",
    "GML",
    "GMLAS",
    "GPKG",
    "GPSBabel",
    "GPX",
    "GTFS",
    "GeoJSON",
    "GeoJSONSeq",
    "GeoRSS",
    "HTTP",
    "Idrisi",
    "Interlis 1",
    "Interlis 2",
    "JML",
    "JSONFG",
    "KML",
    "LIBKML",
    "LVBAG",
    "MBTiles",
    "MEM",
    "MSSQLSpatial",
    "MVT",
    "MapInfo File",
    "MapML",
    "MiraMonVector",
    "NAS",
    "NGW",
    "OAPIF",
    "ODBC",
    "ODS",
    "OGCAPI",
    "OGR_GMT",
    "OGR_PDS",
    "OGR_VRT",
    "OSM",
    "OpenFileGDB",
    "PCIDSK",
    "PDS4",
    "PGDUMP",
    "PGeo",
    "PLSCENES",
    "PMTiles",
    "S101",
    "S57",
    "SQLite",
    "SXF",
    "Selafin",
    "TIGER",
    "TopoJSON",
    "UK .NTF",
    "VDV",
    "VFK",
    "VICAR",
    "WAsP",
    "WFS",
    "XLSX",
]

RASTER_DRIVERS = [
    "AAIGrid",
    "ACE2",
    "ADRG",
    "AIG",
    "AirSAR",
    "BIGGIF",
    "BMP",
    "BSB",
    "BT",
    "BYN",
    "CAD",
    "CALS",
    "CEOS",
    "COASP",
    "COG",
    "COSAR",
    "CPG",
    "CTG",
    "DAAS",
    "DERIVED",
    "DIMAP",
    "DOQ1",
    "DOQ2",
    "DTED",
    "E57",
    "ECRGTOC",
    "EEDAI",
    "EHdr",
    "EIR",
    "ENVI",
    "ERS",
    "ESAT",
    "ESRIC",
    "FAST",
    "GDALG",
    "GFF",
    "GIF",
    "GPKG",
    "GRASSASCIIGrid",
    "GS7BG",
    "GSAG",
    "GSBG",
    "GSC",
    "GTI",
    "GTX",
    "GTiff",
    "GXF",
    "GenBin",
    "HF2",
    "HFA",
    "HTTP",
    "ILWIS",
    "IRIS",
    "ISCE",
    "ISG",
    "ISIS2",
    "ISIS3",
    "Icechunk",
    "JAXAPALSAR",
    "JDEM",
    "JPEG",
    "JPEGXL",
    "KMLSUPEROVERLAY",
    "KRO",
    "L1B",
    "LAN",
    "LCP",
    "LERC",
    "LIBERTIFF",
    "LOSLAS",
    "Leveller",
    "MAP",
    "MBTiles",
    "MEM",
    "MFF",
    "MFF2",
    "MRF",
    "MSGN",
    "MiraMonRaster",
    "NDF",
    "NGSGEOID",
    "NGW",
    "NITF",
    "NOAA_B",
    "NSIDCbin",
    "NTv2",
    "NWT_GRC",
    "NWT_GRD",
    "OGCAPI",
    "OpenFileGDB",
    "PAux",
    "PCIDSK",
    "PCRaster",
    "PDS",
    "PDS4",
    "PLMOSAIC",
    "PLSCENES",
    "PMTiles",
    "PNG",
    "PNM",
    "PRF",
    "RCM",
    "RIK",
    "RMF",
    "ROI_PAC",
    "RPFTOC",
    "RRASTER",
    "RS2",
    "RST",
    "SAFE",
    "SAGA",
    "SAR_CEOS",
    "SENTINEL2",
    "SIGDEM",
    "SNAP_TIFF",
    "SNODAS",
    "SRP",
    "SRTMHGT",
    "STACIT",
    "STACTA",
    "TGA",
    "TIL",
    "TSX",
    "Terragen",
    "USGSDEM",
    "VICAR",
    "VRT",
    "WCS",
    "WEBP",
    "WMS",
    "WMTS",
    "XYZ",
    "ZMap",
    "Zarr",
]
